### ISSUE TITLE
Theme "Twine" without meta!

### ISSUE THREAD

**Issue by no1crate** [kurmachu/retro-docs-site#13]
While I was reading who did every theme, I noticed that the Twine theme doesnt have meta! Instead of showing any meta info like description or creator, it shows the next message:
> Legacy theme? No meta provided.

**Comment by no1crate** [comment]
Just saw that was the legacy theme

**Comment by kurmachu** [comment]
Yeah twine will get meta

Eventually.

**Comment by thekifake** [comment]
I could write some. Would that be preferable, or would you like to write it yourself?

**Comment by donut28** [comment]
I've made a PR that will solve the issue.

**Comment by kurmachu** [comment]
As of 7d7c18853f934eaa848a616c4a2e938c3fc425c4 twine now has meta.
