### ISSUE TITLE
Comply with upstream license, if necessary

### ISSUE THREAD

**Issue by woooferz** [kurmachu/retro-docs-site#20]
Could be MIT, could be something else idk i only use MIT.

**Comment by thekifake** [comment]
If it's going to be given a licence, it should be the same as the original documentation viewer's or at least state what said licence is (if there is any). In any case, I usually just go with the GNU GPLv3 licence.

**Comment by kurmachu** [comment]
Technically, due to the lack of a licence on [the upstream documentation repository](https://github.com/NexTre-dev/retro-gadgets-docs), this entire project is in violation of the default copyright laws. We'll have to wait for @NexTre-dev to add a licence first. If they refuse to, this project technically cannot continue. We're skirting by on the assumption that they simply have not added one yet, and that we've yet to receive a DMCA.

**Comment by kurmachu** [comment]
[I've added an issue to the documentation repository](https://github.com/NexTre-dev/retro-gadgets-docs/issues/26)

**Comment by donut28** [comment]
Hold on- doesn't this repo's code, since it makes derivative works based upon the docs which are on an MIT licence, need to have the same license?

This is our current one:
![image](https://user-images.githubusercontent.com/112806218/203425392-94f41774-581a-4061-b05b-51903dc8f615.png)

**Comment by donut28** [comment]
_The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software._

**Comment by kurmachu** [comment]
No?
![image](https://user-images.githubusercontent.com/31492625/203426092-4c35a09e-a0d7-488e-ba7e-e046e0045b9c.png)

We do however need to provide access to the notice somewhere from the viewer itself. We're compliant (I think, I'm not a lawyer) in both the source stage (this repository does not actually contain any documentation) and in the build stage (as the LICENCE file gets pulled along with the rest of the documentation). This leaves just the distribution stage to be compliant with.

It's also possible that we're fine as the source repository (and the LICENCE file within it) are linked from the site already.

**Comment by thekifake** [comment]
Information on the licence for the viewer and documentation could likely be stated in the info section if it's not too big already.
![image](https://user-images.githubusercontent.com/22648124/203437030-97064dd5-108f-4ae9-8cdc-8571f9251f23.png)

**Comment by donut28** [comment]
Good idea @thekifake

**Comment by kurmachu** [comment]
Thanks for the idea! This has been implemented as of 9969237.
![image](https://user-images.githubusercontent.com/31492625/203451715-f1b7b2b7-a802-4ab1-aac5-c2ff7f31917e.png)
