### ISSUE TITLE
Set default theme to OS

### ISSUE THREAD

**Issue by woooferz** [kurmachu/retro-docs-site#23]
Set the default theme to light/dark depending on OS theme.

**Comment by kurmachu** [comment]
We'd need a default dark theme for this

**Comment by thekifake** [comment]
It'd probably be a good idea to decide on a dark theme to place in the Default folder and use that based on OS. I think it'd be better to make a dark theme based on the colours of Arithm, but another could be chosen based with popular vote or something. I could try to make a basic dark theme to use as the default (evil Arithm).

**Comment by kurmachu** [comment]
I am 100% on board with calling a dark equivalent of Arithm "Evil Arithm"
