### ISSUE TITLE
Theme ver 2

### ISSUE THREAD

**Issue by kurmachu** [kurmachu/retro-docs-site#26]
@thekifake @donut28 @woooferz @no1crate 

**Theme ver 2** is here, bringing the new mobile menu, table properties, and support for blockquote. It's not a super big change, but you do need to update your themes to be compatible, especially with the new mobile menu.

See Arithm for the new properties, and update your meta to 2 when you've upgraded your theme to remove the warning.

Themes not updated within a reasonable amount of time may be liable for removal.

---------------------------------------------------------------------------------------------
ℹ️ _Going forward, table and blockquote theming will be expected in new themes._

**Comment by no1crate** [comment]
I'll do it later because I can't right now.

**Comment by donut28** [comment]
I'll make a PR with all the changes when I can. 👍

**Comment by kurmachu** [comment]
I've updated my themes to ver 2, but I'll keep this issue open incase anyone needs help updating their theme.

**Comment by thekifake** [comment]
I'll get to updating my theme ASAP, and I'll see if I can make another in the process.

**Comment by donut28** [comment]
Gotta love web development for mobile 😭

**Comment by donut28** [comment]
Just made a PR.

**Comment by kurmachu** [comment]
# 🗑️❗ Themes may be deleted starting tomorrow. This is your final warning.

The following contributors have one or more theme not yet updated to ver 2:
@thekifake 
@woooferz 
@no1crate 

Themes with active pull requests will not be removed.

**Comment by no1crate** [comment]
Doing it rn.

**Comment by no1crate** [comment]
The [Pull Request](https://github.com/kurmachu/retro-docs-site/pull/28)

**Comment by kurmachu** [comment]
Outdated themes without a pull request have been removed. If you need the file for a removed theme, the last commit with themes is [7e717d1](https://github.com/kurmachu/retro-docs-site/tree/7e717d114285a8ac3bd005347c1b948a32db8e56).
