### ISSUE TITLE
Upgraded theme switcher (and new font for Arithm)

### ISSUE THREAD

**Issue by kurmachu** [kurmachu/retro-docs-site#31]
![image](https://user-images.githubusercontent.com/31492625/209612354-0d38ff93-8d27-4f26-b702-92265286f3c1.png)

I'm still working on the implementation details. Arithm will use this font ([IBM Plex Sans](https://fonts.google.com/specimen/IBM+Plex+Sans)) if we go through with it. This upgrade should come with other quality of life features, such as being able to name themes something other than their file name, and hopefully fix the flashes on theme change.

**Comment by donut28** [comment]
Yes!!! I was hoping a new theme selector would be released. I made a sketch kinda a while back but I don't think you saw it:

![image](https://user-images.githubusercontent.com/112806218/209622517-4afd01bb-f4eb-4545-8b7f-0b8b2ea27a34.png)

**Comment by thekifake** [comment]
Looks pretty. It scrolls, yes?

**Comment by kurmachu** [comment]
Yeah it would scroll. Not sure if we need it at the moment, because our theme quantity has drastically reduced. It's on hold for now.
