### ISSUE TITLE
Localised strings

### ISSUE THREAD

**Issue by thekifake** [kurmachu/retro-docs-site#33]
If the game's documentation supports multiple languages the viewer should follow suit as well. This can likely be implemented via key-value pairs like this:

```json
{
  "theme-legacy-warning": "This theme has not been updated to the latest specifications, and may display incorrectly."
}
{
  "theme-legacy-warning": "tenpo pali sin la kon ni li sin ala. ona li ken lukin e ike."
}
```

Obviously there is the concern of inline elements (for example, `This is an <strong>inline element</strong>`), but this can easily be fixed with string formatting. It's a feature in many statically-typed languages and is all I can think of to approach this issue, and as far as I can tell there is no JavaScript equivalent but one could be easily implemented.

```json
  "language-add-notice": "Language missing or incomplete? <a href=\"https://github.com/NexTre-dev/retro-gadgets-docs\">%s</a>",
  "language-add-notice-link": "Submit an issue or help translate."
```
```javascript
String.prototype.format = function() {
  // ...
}
console.log(curLocale["language-add-notice"].format(curLocale["language-add-notice-link"]));
```

However this might not work well and will likely further increase the size of the localisation files. A better approach might be to go through the elements in a default string and give them IDs, inserting proper text inbetween with some specific formatting in the localisation strings ... How to do it is up for discussion, and it might be documented somewhere else already.

**Comment by kurmachu** [comment]
There's a few solutions for this, most of which are indeed simply string replacements and the such which can happen during build time. Sadly, this is currently very low priority as all but the english docs are really up-to-date, and while I would wish for proper translations, I don't actually see that happening any time soon. I'll revisit this topic when the need arises, and thank you for your feedback!
